# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/seenum/cs184/Bubble_Rings/sim/CGL/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/seenum/cs184/Bubble_Rings/sim/CGL/src/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.22.2/share/cmake/Modules/FindFreetype.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.22.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.22.2/share/cmake/Modules/FindPackageMessage.cmake))

/Users/seenum/cs184/Bubble_Rings/sim/xcode/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.22.2/bin/cmake -H/Users/seenum/cs184/Bubble_Rings/sim -B/Users/seenum/cs184/Bubble_Rings/sim/xcode
